### ISSUE TITLE
About button should point to preprint

### ISSUE THREAD

**Issue by mcnuttandrew** [tableau/Visualization-Linting#13]

**Comment by mcorrell** [comment]
Do we have a preprint to point to?

**Comment by mcnuttandrew** [comment]
The one on arxiv????? This one https://arxiv.org/abs/2001.02316 ???

**Comment by mcorrell** [comment]
Oh whoops I was confused what repo this issue was in. Yeah, let's link to that. I'll at least put it in the readme.
