### ISSUE TITLE
Should this repo be archived?

### ISSUE THREAD

**Issue by mcnuttandrew** [tableau/Visualization-Linting#67]
It seems like the main activity we've (well just @mcorrell really) been putting into this repo is just updating package versions as they encounter security issues. [The demo](https://metamorphic-linting.netlify.app/) seems to work fine and doesn't ask the user to expose any information and is on a pretty siloed heroku server. 

Given this non-activity I wonder if it might be appropriate to archive this repo. That way: it'd still be available, but wouldn't cause as much as maintenance spam. I also think it's fine to leave it up, but I thought i'd check in.

**Comment by mcorrell** [comment]
I would be fine with archiving, since there's not active development.

**Comment by mcnuttandrew** [comment]
If not being archived, might be good to make it so PRs just automerge so we can stop getting alerts (ala https://github.com/vega/editor/blob/master/.github/workflows/merge-dependabot.yml)

**Comment by mcorrell** [comment]
I don't have permission to archive I think (although I think that's the right call). Auto merging would be nice!

**Comment by bcantoni** [comment]
Confirmed with some folks still at Tableau and we agree this should be archive.
